name: Build(platformio)

on:
  push:
    tags-ignore:
      - '*.*.*'
      - 'v*.*.*'
    branches:
      - '*'
    paths:
      - 'src/unit/**.cpp'
      - 'src/unit/**.hpp'
      - 'src/unit/**.h'
      - 'src/unit/**.c'
      - 'test/**.cpp'
      - 'test/**.hpp'
      - 'test/**.h'
      - 'test/**.c'
      - 'examples/UnitUnified/**.ino'
      - 'examples/UnitUnified/**.cpp'
      - 'examples/UnitUnified/**.hpp'
      - 'examples/UnitUnified/**.h'
      - 'examples/UnitUnified/**.c'
      - '/platformio-build-check.yml'
      - '**platformio.ini'
  pull_request:
    paths:
      - 'src/unit/**.cpp'
      - 'src/unit/**.hpp'
      - 'src/unit/**.h'
      - 'src/unit/**.c'
      - 'test/**.cpp'
      - 'test/**.hpp'
      - 'test/**.h'
      - 'test/**.c'
      - 'examples/UnitUnified/**.ino'
      - 'examples/UnitUnified/**.cpp'
      - 'examples/UnitUnified/**.hpp'
      - 'examples/UnitUnified/**.h'
      - 'examples/UnitUnified/**.c'
      - '**/platformio-build-check.yml'
      - '**platformio.ini'
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.unit }}:${{ matrix.example }}@${{ matrix.board }}:${{ matrix.framework }}:${{ matrix.espressif32 }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: false
      max-parallel: 20
      
      matrix:
        example:
          - PlotToSerial

        unit:
          - UnitUltraSonic

        board:
          - Core
          - Core2
          - CoreS3
          - Fire
          - StampS3
          - Dial
          - AtomMatrix
          - AtomS3
          - AtomS3R
          - NanoC6
          - StickCPlus
          - StickCPlus2
          - Paper
          - CoreInk

        framework:
          - Arduino

        espressif32:
          - latest

        include:
          # Specific sketches
          - example: DualSensor
            unit: UnitUltraSonic
            board: Core
            framework: Arduino
            espressif32: latest
          - example: DualSensor
            unit: UnitUltraSonic
            board: Core2
            framework: Arduino
            espressif32: latest
          - example: DualSensor
            unit: UnitUltraSonic
            board: CoreS3
            framework: Arduino
          - example: DualSensor
            unit: UnitUltraSonic
            board: Fire
            framework: Arduino
          - example: DualSensor
            unit: UnitUltraSonic
            board: Paper
            framework: Arduino

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build examples
        uses: karniv00l/platformio-run-action@v1
        with:
          environments: ${{ matrix.unit != '' && format('{0}_{1}_{2}_{3}_{4}', matrix.unit, matrix.example, matrix.board, matrix.framework, matrix.espressif32) || format('{0}_{1}_{2}_{3}', matrix.example, matrix.board, matrix.framework, matrix.espressif32) }}
#         targets:
          project-dir: "./"
          project-conf: "./platformio.ini"
#          jobs: 6
#          silent: false
#          verbose: true
#          disable-auto-clean: false

